remote_theme: gaalcaras/academic

baseurl: ""
author: Pan Kessel
title: Pan Kessel
title_html: "<b>P</b>an<b><span class=\"invisible\"> </span>kessel</b>"
langs: ["en"]
defaults:
    - scope:
        path: ""
      values:
        lang: "en"
email: pan.kessel@gmail.com
github_username: pankessel
twitter_username: daspantom
cc: by

nav_ext_links:
    - name: Google Scholar
      url:
          en: https://scholar.google.com/citations?user=uODjwl8AAAAJ&hl=en
